version: "3.8"

services:
  app:
      depends_on:
        - mongodb
      build: .
      restart: on-failure
      env_file: .env
      ports:
        - "8080:8080"
#      environment:
#        MONGODB_DATABASE: ${MONGODB_DATABASE}
#        MONGODB_USERNAME: ${MONGODB_USERNAME}
#        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
#        SPRING_APPLICATION_JSON: '{
#          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
#          "spring.datasource.username" : "$MYSQLDB_USER",
#          "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
#          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
#          "spring.jpa.hibernate.ddl-auto" : "update"
#        }'
      volumes:
        - .m2:/root/.m2
      stdin_open: true
#      TODO sprawdzic co to
      tty: true
#      TODO sprawdzic co to

  mongodb:
    image: mongo:4.4.5
    container_name: mongodb
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE:-city-list-db}
      MONGODB_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-admin}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo_volume:/data/db

volumes:
  mongo_volume: