version: "3.8"

services:
  app:
    depends_on:
      - mongodb
    build: .
    restart: on-failure
    env_file: .env
    ports:
      - "${CONTAINER_PORT}:${APP_PORT}"
    volumes:
      - .m2:/root/.m2

  mongodb:
    image: mongo:4.4.5
    container_name: mongodb
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE:-city-list-db}
      MONGODB_USERNAME: ${MONGODB_USERNAME:-admin}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD:-admin}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo_volume:/data/db

volumes:
  mongo_volume: